version: "3.8"

services:
    redis_db:
        container_name: redis_db
        command: bash -c "redis-server --appendonly yes"
        image: redis
        ports:
            - "6379:6379"
        volumes:
            - ./redis-volume:/data
        networks:
            - microservices

    postgres_db:
        image: postgres
        environment:
            POSTGRES_PASSWORD: "senha_trabalho_unifei"
        ports:
            - "15432:5432"
        volumes:
            - ./postgres-volume:/var/lib/postgresql/data
        networks:
            - microservices

    pgadmin:
        image: dpage/pgadmin4
        environment:
            PGADMIN_DEFAULT_EMAIL: "lucasblazzi@hotmail.com"
            PGADMIN_DEFAULT_PASSWORD: "senha_trabalho_unifei"
        ports:
            - "16543:80"
        depends_on:
            - postgres_db
        networks:
            - microservices

    client_service:
        build:
            context: .
            dockerfile: client/Dockerfile
        image: client
        networks:
            - microservices
        ports:
            - 5001:5001

    advisor_service:
        build:
            context: .
            dockerfile: advisor/Dockerfile
        image: advisor
        networks:
            - microservices
        ports:
            - 5002:5002

    assets_service:
        build:
            context: .
            dockerfile: assets/Dockerfile
        image: assets
        networks:
            - microservices
        ports:
            - 5003:5003

networks:
    microservices:
        driver: bridge